### ISSUE TITLE
Update for elm.19 ?

### ISSUE THREAD

**Issue by aaahrens** [billstclair/elm-sha256#4]
Could you please update the library for elm.19? I like this library for pkce auth code stuff.

**Comment by billstclair** [comment]
Sorry I've been slow to get to this. I'll do it soon. I was going to recommend using ktonon/elm-crypto instead, but it also hasn't yet been upgraded to 0.19.

**Comment by billstclair** [comment]
I finally upgraded this to 0.19.

I tossed the example. Since native modules no longer work, there's nothing to compare it to.

**Comment by aaahrens** [comment]
I could make an example for the PKCE auth flow? I mean that really one of the only reason for 256 nowadays >.>

**Comment by aaahrens** [comment]
also ty for the upgrade

**Comment by billstclair** [comment]
> I could make an example for the PKCE auth flow? I mean that really one of the only reason for 256 nowadays >.>

Thanks for the offer, but not really necessary. People who need SHA256 pretty much know why. The old example was just a way to compare performance of three different implementations. I suppose I could time the native JS through a port, but not worth the effort.

**Comment by billstclair** [comment]
Fixed by 7f4a734
